### ISSUE TITLE
small typo in addsyncjob commandline example

### ISSUE THREAD

**Issue by PiotrEsse** [appcoders/mailcowtools#3]
In 
https://github.com/appcoders/mailcowtools/tree/master/addSyncJobs

in description theres a typo in example -  now its "-host1" but should be "--host1"

**Comment by appcoders** [comment]
Thanks @PiotrEsse - its fixed now in https://github.com/appcoders/mailcowtools/commit/5a3e2f6694449766d4234bcfb4d9336c1020f84b
